### ISSUE TITLE
abs.threshold issue

### ISSUE THREAD

**Issue by janaltman** [pavel-fibich/TRADER#3]
1) nevim vubec k cemu je tam parametr "abs" u funkce "absoluteIncreaseALL" (ale to neni tak dulezite, i kdyz by me to zajimalo :-))

2) vic dulezite je, ze u funkce "doAll" nefunguje nastaveni "abs.threshold". Proste si to pocita samo tu absolutni hranici podle zadanych parametru a neda se to jakkoliv zmenit (ne ze  by se jednalo o neco zasadniho, ale prislo by mi sikovne mit tam automaticky "NULL", ale umoznit, to zmenit, pokud by nekdo chtel).

**Comment by pavel-fibich** [comment]
1) check ?absoluteIncreaseAll
2) solved in 1.2-2
