### ISSUE TITLE
doall

### ISSUE THREAD

**Issue by janaltman** [pavel-fibich/TRADER#5]
Spis dotaz (protoze do toho neni videt). Funkce "doAll" ma moznost nastaveni: criteria = 0.2, criteria2 = 0.5, 	segment = 0.5, segment2 = 0.5. Nicmene to je asi neco co leze do vsech tech funkci, co? Bylo by lepsi, kdyby criteria (obe dve) sli nastavit pro ty tri metody (absolute increase je zvlast, k tomu mam komentar v jinem issue) a segmenty by  meli jit nastavit u boundary line a splechtna. Tj asi idealne by tam melo byt neco jako: criteriaN&A, criteriaBL a criteriaS. a to same u segmentu (segmentBL a sementS). Ostatni parametry uz myslim zvlast byt nemusi, ale v techle se ty funkce odlisuji a ted je tim vlastne sjednocujem.

**Comment by pavel-fibich** [comment]
solved in 1.2-2
