### ISSUE TITLE
jednotny styl csv souboru

### ISSUE THREAD

**Issue by janaltman** [pavel-fibich/TRADER#7]
Je to blbost, ale exportovane .csv soubory maji odlisne separatory (min. tam je tabulator a mezera) a urcite by bylo jednodusi, kdyby v ramci jednoho baliku slo pak pri importu pouzit vzdy jeden prikaz a ne pro kazdy soubor jiny

**Comment by pavel-fibich** [comment]
all in csv, solved in 1.2-2
